conservador:
  SCORE_BUY_MIN: 80
  DD_BUY: -0.30
  DD_STRONG: -0.40
  REQUIRE_PASS_DEBT: true
  REQUIRE_PASS_INTEREST: true
  REQUIRE_PASS_FCF: true
  REQUIRE_PASS_ROIC: true
  REQUIRE_PASS_PAYOUT: true
  ALLOW_SPECULATIVE: false

balanceado:
  SCORE_BUY_MIN: 70
  DD_BUY: -0.20
  DD_STRONG: -0.30
  REQUIRE_PASS_DEBT: true
  REQUIRE_PASS_INTEREST: true
  REQUIRE_PASS_FCF: true
  REQUIRE_PASS_ROIC: true
  REQUIRE_PASS_PAYOUT: false
  ALLOW_SPECULATIVE: true

agressivo:
  SCORE_BUY_MIN: 60
  DD_BUY: -0.10
  DD_STRONG: -0.20
  REQUIRE_PASS_DEBT: false
  REQUIRE_PASS_INTEREST: false
  REQUIRE_PASS_FCF: true
  REQUIRE_PASS_ROIC: false
  REQUIRE_PASS_PAYOUT: false
  ALLOW_SPECULATIVE: true
